### ISSUE TITLE
ValueError: u'59248f9895d0e024b5872783' is not in list when training

### ISSUE THREAD

**Issue by devdev999** [furkanbiten/GoodNews#11]
I encounter this when trying to train:

Traceback (most recent call last):
  File "train.py", line 283, in <module>
    train(opt)
  File "train.py", line 139, in train
    data = loader.get_batch('train')
  File "/im2p/GoodNews-master/dataloader.py", line 261, in get_batch
    sen_ixs = [self.sen_embed_keys.index(key) for key in keys]
ValueError: u'59248f9895d0e024b5872783' is not in list
Closing remaining open files:./data/data_news_image.h5...done./data/data_news_label.h5...done

**Comment by xiaodan9377** [comment]
Have the same issue. Anyone can help?

**Comment by fresh382227905** [comment]
> Have the same issue. Anyone can help?

have you solved this problem?

**Comment by devdev999** [comment]
> > Have the same issue. Anyone can help?
> 
> have you solved this problem?

Don't bother, I solved this by removing it from the list of articles, but there are many more errors like this down the road. The authors are intentionally obfuscating the code.
